name: elevatorsimulator
description: elevatorsimulator
publish_to: 'none'
version: 1.2.1+31

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^1.10.6
  firebase_analytics: ^8.3.4
  # App Icon
  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  # Floating Button
  flutter_speed_dial: ^5.0.0+1
  # HyperLink
  url_launcher: ^6.0.17
  # Text to Speech
  flutter_tts: ^3.2.3
  # Audio Player
  audioplayers: ^0.20.1
  # Vibration
  vibration: ^1.7.4-nullsafety.0
  # Admob
  google_mobile_ads: ^1.0.1
  app_tracking_transparency: ^2.0.2+1
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.1
  # App Splash
  flutter_native_splash: ^1.3.1

flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "f7b249"
  adaptive_icon_foreground: "images/appIcon.png"

flutter_native_splash:
  image: "images/icon.png"
  color: "f7b249"

flutter:
  # Localize
  generate: true
  uses-material-design: true
  assets:
    - images/1.png
    - images/2.png
    - images/3.png
    - images/4.png
    - images/5.png
    - images/6.png
    - images/7.png
    - images/8.png
    - images/14.png
    - images/100.png
    - images/154.png
    - images/B1.png
    - images/B2.png
    - images/B3.png
    - images/B4.png
    - images/R.png
    - images/p1.png
    - images/p2.png
    - images/p3.png
    - images/p4.png
    - images/p5.png
    - images/p6.png
    - images/p7.png
    - images/p8.png
    - images/p14.png
    - images/p100.png
    - images/p154.png
    - images/pB1.png
    - images/pB2.png
    - images/pB3.png
    - images/pB4.png
    - images/pR.png
    - images/circle.png
    - images/pressedCircle.png
    - images/button.png
    - images/pButton.png
    - images/open.png
    - images/pressedOpen.png
    - images/sOpen.png
    - images/sPressedOpen.png
    - images/close.png
    - images/pressedClose.png
    - images/sClose.png
    - images/sPressedClose.png
    - images/phone.png
    - images/pressedPhone.png
    - images/sPhone.png
    - images/sPressedPhone.png
    - images/up.png
    - images/down.png
    - images/shimada.png
    - assets/call.mp3
    - assets/pon.mp3
    - assets/popi.mp3
    - assets/tetete.mp3

  fonts:
    - family: teleIndicators
      fonts:
        - asset: fonts/teleindicadores.ttf
