name: letselevator
description: elevatorsimulator
publish_to: 'none'
version: 1.5.13+94

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_android: ^4.9.1
  webview_flutter: ^4.13.0

  # Firebase Analytics
  firebase_core: ^3.15.2
  firebase_core_web: ^2.24.1
  firebase_analytics: ^11.6.0
  firebase_analytics_web: ^0.5.10+16
  firebase_app_check: ^0.3.2+10
  # App Icon
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  # HyperLink
  path: ^1.9.1
  url_launcher: ^6.3.2
  url_launcher_web: ^2.4.1
  # Text to Speech
  flutter_tts: ^4.2.3
  # Audio Player
  just_audio: ^0.10.4
  # audioplayers: ^6.5.0
  # Vibration
  vibration: ^3.1.3
  #  Game Center
  games_services: ^4.1.1
  # Shared Preference
  shared_preferences: ^2.5.3
  shared_preferences_web: ^2.4.3
  # Admob
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.6+1
  #env
  flutter_dotenv: ^5.2.1
  #MVVM
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  # App Splash
  flutter_native_splash: ^2.4.6

  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#f7b249"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "#f7b249"
  android_12:
    image: "assets/images/menu/icon.png"
    icon_background_color: "#f7b249"
  ios: false
  web: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/common/
    - assets/images/menu/
    - assets/images/normalMode/
    - assets/images/1000Mode/
    - assets/images/realOn/
    - assets/images/realOff/
    - assets/images/real1000On/
    - assets/images/real1000Off/
    - assets/images/real1000On/p1/
    - assets/images/real1000On/p2/
    - assets/images/real1000On/p3/
    - assets/images/real1000On/p4/
    - assets/images/real1000On/p5/
    - assets/images/real1000On/p6/
    - assets/images/real1000On/p7/
    - assets/images/real1000On/p8/
    - assets/images/real1000On/p9/
    - assets/images/real1000Off/1/
    - assets/images/real1000Off/2/
    - assets/images/real1000Off/3/
    - assets/images/real1000Off/4/
    - assets/images/real1000Off/5/
    - assets/images/real1000Off/6/
    - assets/images/real1000Off/7/
    - assets/images/real1000Off/8/
    - assets/images/real1000Off/9/
    - assets/images/button/
    - assets/images/settings/
    - assets/.env

  fonts:
    #For title font
    - family: cornerstone
      fonts:
        - asset: assets/fonts/cornerstone.ttf
    #For English, Spanish, French font
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    #For Japanese font
    - family: notoJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.ttf
    #For Chinese font
    - family: notoSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Bold.ttf
    #For Korean font
    - family: bmDohyeon
      fonts:
        - asset: assets/fonts/bm-dohyeon.regular.ttf
    #For dot number
    - family: lcd
      fonts:
        - asset: assets/fonts/5x8_lcd_hd44780u_a02.ttf
    #For digital number
    - family: dseg
      fonts:
        - asset: assets/fonts/DSEG7Classic-BoldItalic.ttf
    #For digital alphabet
    - family: letsgo
      fonts:
        - asset: assets/fonts/letsgodigital.ttf
