name: letselevator
description: elevatorsimulator
publish_to: 'none'
version: 1.4.0+60

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^2.13.0
  firebase_analytics: ^10.4.2
  # App Icon
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.13.0
  # Svg
  flutter_svg: ^2.0.5
  # HyperLink
  url_launcher: ^6.1.11
  # Font
  google_fonts: ^4.0.4
  # Text to Speech
  flutter_tts: ^3.6.3
  # Audio Player
  audioplayers: ^3.0.1
  # Vibration
  vibration: ^1.7.7
  #  Game Center
  #  games_services: ^ 2.2.0
  # BLE
  #  flutter_blue: ^0.8.0
  # Connectivity
  connectivity_plus: ^4.0.1
  # Shared Preference
  shared_preferences: ^2.1.1
  # Admob
  google_mobile_ads: ^3.0.0
  app_tracking_transparency: ^2.0.4
  #env
  flutter_dotenv: ^5.0.2
  #MVVM
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # App Splash
  flutter_native_splash: ^2.3.0

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "f7b249"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "f7b249"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/common/
    - assets/images/normalMode/
    - assets/images/1000Mode/
    - assets/images/realOn/
    - assets/images/realOff/
    - assets/images/real1000On/
    - assets/images/real1000Off/
    - assets/images/real1000On/p1/
    - assets/images/real1000On/p2/
    - assets/images/real1000On/p3/
    - assets/images/real1000On/p4/
    - assets/images/real1000On/p5/
    - assets/images/real1000On/p6/
    - assets/images/real1000On/p7/
    - assets/images/real1000On/p8/
    - assets/images/real1000On/p9/
    - assets/images/real1000Off/1/
    - assets/images/real1000Off/2/
    - assets/images/real1000Off/3/
    - assets/images/real1000Off/4/
    - assets/images/real1000Off/5/
    - assets/images/real1000Off/6/
    - assets/images/real1000Off/7/
    - assets/images/real1000Off/8/
    - assets/images/real1000Off/9/
    - assets/.env

  fonts:
    - family: teleIndicators
      fonts:
        - asset: assets/fonts/teleindicadores.ttf
    - family: cornerstone
      fonts:
        - asset: assets/fonts/cornerstone.ttf
    - family: noto
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
