name: letselevator
description: elevatorsimulator
publish_to: 'none'
version: 1.2.13+43

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^1.10.6
  firebase_analytics: ^9.1.0
  # App Icon
  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  # Floating Button
  flutter_speed_dial: ^5.0.0+1
  # HyperLink
  url_launcher: ^6.0.17
  # Font
  google_fonts: ^2.3.1
  # Text to Speech
  flutter_tts: ^3.2.3
  # Audio Player
  audioplayers: ^0.20.1
  # Vibration
  vibration: ^1.7.4-nullsafety.0
  # Shared Preference
  shared_preferences: ^2.0.6
  # Admob
  google_mobile_ads: ^1.0.1
  app_tracking_transparency: ^2.0.2+1
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.1
  # App Splash
  flutter_native_splash: ^2.0.2

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "f7b249"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "f7b249"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/common/
    - assets/images/normalMode/
    - assets/images/1000Mode/
    - assets/images/realOn/
    - assets/images/realOff/
    - assets/audios/

  fonts:
    - family: teleIndicators
      fonts:
        - asset: assets/fonts/teleindicadores.ttf
