name: elevatorsimulator
description: elevatorsimulator
publish_to: 'none'
version: 1.1.0+10

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # App Icon
  flutter_launcher_icons: ^0.9.1
  # Text to Speech
  flutter_tts: ^3.2.1
  # Assets Audio Player
  assets_audio_player: ^3.0.3+6
  # Admob
  google_mobile_ads: ^0.13.2+1
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.1
  # App Splash
  flutter_native_splash: ^1.2.0

flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "ff9800"
  adaptive_icon_foreground: "images/appicon.png"

flutter_native_splash:
  image: "images/icon.png"
  color: "ff9800"

flutter:
  # Localize
  generate: true
  uses-material-design: true
  assets:
    - images/open.png
    - images/close.png
    - images/phone.png
    - images/pressedOpen.png
    - images/pressedClose.png
    - images/pressedPhone.png
    - images/up.png
    - images/down.png
    - audios/call.mp3
    - audios/pon.mp3
    - audios/popi.mp3

  fonts:
    - family: teleIndicators
      fonts:
        - asset: fonts/teleindicadores.ttf


