name: elevatorsimulator
description: elevatorsimulator
publish_to: 'none'
version: 1.2.6+36

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^1.10.6
  firebase_analytics: ^8.3.4
  # App Icon
  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  # Floating Button
  flutter_speed_dial: ^5.0.0+1
  # HyperLink
  url_launcher: ^6.0.17
  # Text to Speech
  flutter_tts: ^3.2.3
  # Audio Player
  audioplayers: ^0.20.1
  # Vibration
  vibration: ^1.7.4-nullsafety.0
  # Admob
  google_mobile_ads: ^1.0.1
  app_tracking_transparency: ^2.0.2+1
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.1
  # App Splash
  flutter_native_splash: ^1.3.1

flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "f7b249"
  adaptive_icon_foreground: "images/appIcon.png"

flutter_native_splash:
  image: "images/icon.png"
  color: "f7b249"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/normalMode/
    - images/1000ButtonsMode/
    - images/1000ButtonsOn/
    - images/1000ButtonsOff/
    - images/button.png
    - images/pButton.png
    - images/up.png
    - images/down.png
    - images/title1000Buttons.jpg
    - images/transparent.png
    - assets/call.mp3
    - assets/pon.mp3
    - assets/popi.mp3
    - assets/tetete.mp3

  fonts:
    - family: teleIndicators
      fonts:
        - asset: fonts/teleindicadores.ttf
