name: letselevator
description: elevatorsimulator
publish_to: 'none'
version: 1.4.10+70

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter

  # Firebase Analytics
  firebase_core: ^2.31.0
  firebase_analytics: ^10.10.5
  # App Icon
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  # HyperLink
  url_launcher: ^6.2.6
  # Font
  google_fonts: ^6.2.1
  # Text to Speech
  flutter_tts: ^4.0.2
  # Audio Player
  audioplayers: ^6.0.0
  # Vibration
  vibration: ^1.8.4
  #  Game Center
  games_services: ^4.0.1
  # Shared Preference
  shared_preferences: ^2.2.3
  # Admob
  google_mobile_ads: ^5.0.0
  app_tracking_transparency: ^2.0.5
  #env
  flutter_dotenv: ^5.1.0
  #MVVM
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # App Splash
  flutter_native_splash: ^2.4.0

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#f7b249"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "#f7b249"
  android_12:
    image: "assets/images/menu/icon.png"
    icon_background_color: "#f7b249"
  ios: false
  web: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/common/
    - assets/images/menu/
    - assets/images/normalMode/
    - assets/images/1000Mode/
    - assets/images/realOn/
    - assets/images/realOff/
    - assets/images/real1000On/
    - assets/images/real1000Off/
    - assets/images/real1000On/p1/
    - assets/images/real1000On/p2/
    - assets/images/real1000On/p3/
    - assets/images/real1000On/p4/
    - assets/images/real1000On/p5/
    - assets/images/real1000On/p6/
    - assets/images/real1000On/p7/
    - assets/images/real1000On/p8/
    - assets/images/real1000On/p9/
    - assets/images/real1000Off/1/
    - assets/images/real1000Off/2/
    - assets/images/real1000Off/3/
    - assets/images/real1000Off/4/
    - assets/images/real1000Off/5/
    - assets/images/real1000Off/6/
    - assets/images/real1000Off/7/
    - assets/images/real1000Off/8/
    - assets/images/real1000Off/9/
    - assets/.env

  fonts:
    - family: teleIndicators
      fonts:
        - asset: assets/fonts/teleindicadores.ttf
    - family: cornerstone
      fonts:
        - asset: assets/fonts/cornerstone.ttf
    - family: noto
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
