// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1b8eqTGR3hTuMWTat95YSK9AyLPCJ4jo',
    appId: '1:265404624074:android:d2d8f585b2abfa1ddad833',
    messagingSenderId: '265404624074',
    projectId: 'elevator-simulator-app',
    storageBucket: 'elevator-simulator-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCer1xW25fj-oYD-w3jqJys3YRXkapZ1o0',
    appId: '1:265404624074:ios:80761ae465775110dad833',
    messagingSenderId: '265404624074',
    projectId: 'elevator-simulator-app',
    storageBucket: 'elevator-simulator-app.appspot.com',
    androidClientId: '265404624074-a4dn83ap8jktvaptto4rgvm5pg6tm62j.apps.googleusercontent.com',
    iosClientId: '265404624074-06td2elmh0kp1bf0ka4so21cac1qjll2.apps.googleusercontent.com',
    iosBundleId: 'nakajimamasao.appstudio.letselevator',
  );
}
